---
title: "Workshop Notes"
author: "Villaseñor-Derbez, J.C."
date: "`r paste0('Last update: ',format(Sys.Date(), '%B %d, %Y'))`"
output: 
  html_document:
    fig_caption: yes
    toc: yes
    toc_collapse: no
    toc_float: yes
---

# 2018

- Feb 2 - 3, [`Rstudio::conf(2018L)`](./Rstudio2018/) at `Rstudio::conf(2018L)`

- January 31 - Feb 1, [BigData in R](https://rawgit.com/jcvdav/bigdataclass2018/master/assets/workbook/_book/index.html) by [Edgar Ruiz](https://github.com/edgararuiz) at `Rstudio::conf(2018L)`

- January 19, [STAN](./STAN/) by Dan Ovando (5/5)

- January 17, [Data visualization with `ggplot2`](./DataVis/) by Allison Horst @ Eco-Data Science (5/5)

# 2017

- December, [Machine Learning with R](./SLR/) by [DataCamp](https://www.datacamp.com/tracks/machine-learning) (5/5)

- November 16, [Intro to Global Fishing Watch](./GFW/) by SFG's Juan Mayorga (5/5)

- November 1, [Intro to R Markdown](http://www.villasenor-derbez.com/intro2Rmd/CourseMaterials/intro2Rmd.nb.html) by Me @ Eco-Data Science

- October 19, [Python for scientific computing](./Python/) by UCSB's Center for scientifi computing (1/5)

- October 11, [R for Scientific computing](./R4ScComp/) by UCSB's Center for scientific computing (1/5)

- October 4, [Spatial analysis in R with `sf` and `raster`](./SpatialAnalysisSF/) by Jamie Afflerbach @ Eco-Data Science (4/5)

- July 22, [Causal Inference for Conservation Biologists](./ICCBCausalInference/) by Dr. Achaz von Hardenberg [\@achazhardenberg](https://twitter.com/achazhardenberg) (5/5)

- Sometine in the past [Reference Managing in R](https://tclavelle.github.io/blog/reference_tips/) by Tyler Claveller @ Eco-Data Science (4/5)

- February 17, [Practicing `purrr`](./LearnPurrr/) by Dan Ovando @ Eco-Data Science (4/5)

# 2016

- February 11, [Time Series Analysis](./TimeSeries/) by Allison Horst @ ESM 244

